[providers]
python = "3.11"
nodejs = "18"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install --upgrade pip"]

[phases.build] 
dependsOn = ["install"]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm install && npm run build"
]

[phases.start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"